### PR TITLE
Fix manual activities

### LINKED ISSUE #26: Investigate the issue with manualActivities
The manual activity POST from garmin is failing with -
```
[2021-06-22 07:47:59,034] ERROR - [400] http://radarbase-backend.co.uk:80/push/integrations/garmin/manualActivities: The activities data was invalid.
[2021-06-22 07:47:59,034] HTTP  - [400] POST garmin/manualActivities <application/json;charset=UTF-8: 664> -- <null> 
```
This used to be the same as activities data with the manual flag set to true.
Investigate the structure of the data (in case this has changed from the normal activities data).

### PR DESCRIPTION
**Pull request by yatharthranjan**
- The data payload is the same as activities but the root element has a different key.

Closes #26

### CODE REVIEW

File: src/main/kotlin/org/radarbase/push/integration/garmin/service/GarminHealthApiService.kt [hunk 1]
```diff
@@ -107,7 +110,9 @@ class GarminHealthApiService(
 
     @Throws(IOException::class, BadRequestException::class)
     fun processManualActivities(tree: JsonNode, user: User): Response {
-        return this.processActivities(tree, user)
+        val records = manualActivitiesConverter.validateAndConvert(tree, user)
+        producerPool.produce(manualActivitiesConverter.topic, records)
+        return Response.status(OK).build()
```
Comment (blootsvoets) [inline src/main/kotlin/org/radarbase/push/integration/garmin/service/GarminHealthApiService.kt:115]: Alternatives:
- Don't return a OK response, it is the default response by Jersey so it will be redundant.
- Use the shortcut `Response.ok().build()`.

**Review by blootsvoets — APPROVED** [review]
LGTM

File: src/main/kotlin/org/radarbase/push/integration/garmin/service/GarminHealthApiService.kt (hunk 1 above)
Comment (yatharthranjan) [reply src/main/kotlin/org/radarbase/push/integration/garmin/service/GarminHealthApiService.kt:115]: The second alternative looks good to me. It offers flexibility to be changed if required in the future.
